# Generated by Django 3.0.4 on 2020-03-18 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('parent', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'category',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
                ('cid', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.SET_DEFAULT, to='board.Category')),
            ],
            options={
                'verbose_name': 'post',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.Post')),
            ],
            options={
                'verbose_name': 'comment',
                'ordering': ['id'],
            },
        ),
    ]
